easy_admin:
    site_name: 'Administration du site du CASC'
    show:
        max_results: 20
    design:
        brand_color: 'rgba(26, 188, 156, 0.85)'
        assets:
            css:
            js:
            favicon: '/assets/backend/favicon.png'
        menu:
            - label: 'Operations'
              children:
                    -
                        entity: 'Operation'
                        label: 'Fiche'
                    -
                        entity: 'OperationData'
                        label: 'Financement'
            - label: 'Structure'
              children:
                    -
                        entity: 'RegroupementOpe'
                    -
                        entity: 'Quartier'
                    -
                        entity: 'CodeMaire'
                    -
                        entity: 'NatureOpe'
                    -
                        entity: 'PolitiquePub'
            - label: 'Menus'
              children:
                    -
                        entity: 'Menu'
            - label: 'Utilisateurs'
              children:
                    -
                        entity: 'User'
                        icon: 'user'
    list:
        actions:
            - {name: 'edit', icon: 'pencil', label: false, title: 'Edit'}
            - {name: '-delete', icon: 'remove', label: false, title: 'Delete'}
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y'
        number: '%.2f'
    entities:
        # List the entity class name you want to manage
        Quartier:
            class: App\Entity\Admin\Quartier
            label: 'Quartier'
            help: 'Gestion des quartiers'
            list:
                title: 'Liste des quartiers'
            form:
                title: 'Ajout quartier'
                form_options: { validation_groups: ['Default'] }
                fields:
                    - id
                    #- {property: 'images', icon: 'customer', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Objet\Illustration' }}
                    - { property: 'libelle'}
                    - { property: 'code'}
            new:
                help: 'Quartier : ajout'
                form_options: { validation_groups: ['Default'] }
                fields:
                    - '-id'
            edit:
                help: 'Quartier : modification'
                title: 'Edit quartier'
                fields:
                    - '-id'
        CodeMaire:
            show:
                max_results: 5
            class: App\Entity\Admin\CodeMaire
            label: "Code Maire"
            list:
                title: "Liste des CodeMaire"
            form:
                title: "Ajout d'un nouveau CodeMaire"
                form_options: { validation_groups: ['Default'] }
                fields:
                    - { property: 'libelle'}
                    - { property: 'code'}
        NatureOpe:
            show:
                max_results: 5
            class: App\Entity\Admin\NatureOpe
            label: "NatureOpe"
            list:
                title: "Liste des NatureOpe"
            form:
                title: "Ajout d'un nouveau NatureOpe"
                form_options: { validation_groups: ['Default'] }
                fields:
                    - { property: 'libelle'}
        PolitiquePub:
            show:
                max_results: 5
            class: App\Entity\Admin\PolitiquePub
            label: "PolitiquePub"
            list:
                title: "Liste des PolitiquePub"
            form:
                title: "Ajout d'un nouveau PolitiquePub"
                form_options: { validation_groups: ['Default'] }
                fields:
                    - { property: 'id'}
                    - { property: 'libelle'}
        RegroupementOpe:
            show:
                max_results: 5
            class: App\Entity\Admin\RegroupementOpe
            label: "RegroupementOpe"
            list:
                title: "Liste des RegroupementOpe"
            form:
                title: "Ajout d'un nouveau RegroupementOpe"
                form_options: { validation_groups: ['Default'] }
                fields:
                    - { property: 'libelle'}
                    #- {property: 'evenements', type: 'easyadmin_autocomplete'}
        Operation:
            class: App\Entity\Admin\Operation
            label: 'Les fiches'
            list:
                title: "Liste des fiches"
            form:
                title: 'Ajout fiche'
                form_options: { validation_groups: ['Default'] }
                fields:
                    - {type: 'tab', columns: 2, label: 'Information de base'}
                    - id
                    - {property: 'code'}
                    - {property: 'libelle'}
                    - {property: 'description'}
                    - {property: 'commentaire'}
                    - {type: 'tab', columns: 2, label: 'Structure'}
                    - {property: 'RegroupementOpe', icon: 'customer', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Admin\RegroupementOpe' }}
                    - {property: 'Quartier', icon: 'customer', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Admin\Quartier' }}
                    - {property: 'CodeMaire', icon: 'customer', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Admin\CodeMaire' }}
                    - {property: 'NatureOpe', icon: 'customer', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Admin\NatureOpe' }}
                    - {property: 'PolitiquePub', icon: 'customer', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Admin\PolitiquePub' }}
                    - {type: 'tab', columns: 2, label: 'Financements'}
                    # - 
                    #     property: 'OperationData'
                    #     icon: 'customer'
                    #     type: 'easyadmin_autocomplete'
                    #     type_options:
                    #         class: 'App\Entity\Admin\OperationData'
            new:
                help: 'Fiche : ajout'
                form_options: { validation_groups: ['Default', 'Event'] }
                fields:
                    - '-id'
                    - '-tab'
            edit:
                help: 'Fiche : modification'
                title: 'Edit fiche'
                fields:
                    - '-id'
        OperationData:
            class: 'App\Entity\Admin\OperationData'
            label: 'Les financements'
            list:
                title: "Liste des financements"
            form:
                title: 'Ajout financements'
                form_options: { validation_groups: ['Default'] }
                fields:
                    - {type: 'group', columns: 2, label: 'Information de base'}
                    - id
                    - {property: 'Operation', icon: 'customer', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Admin\Operation' }}
                    - {property: 'annee'}
                    - {property: 'montant'}
                    - {property: 'type'}
            new:
                help: 'financement : ajout'
                form_options: { validation_groups: ['Default', 'Event'] }
                fields:
                    - '-id'
            edit:
                help: 'financements : modification'
                title: 'Edit financements'
                fields:
                    - '-id'
        #Notification:
        #    class: App\Entity\Objet\Notification
        #    label: 'Mes notifications'
        #    list:
        #        title: 'Liste des notifications'
        #    form:
        #        title: "Ajout d'une notifications"
        #        form_options: { validation_groups: ['Default'] }
        #        fields:
        #            - {type: 'tab', columns: 2, label: 'Informations de base'}
        #            - id
        #            - {property: 'libelle', icon: 'customer'}
        #            - {property: 'reference', icon: 'customer'}
        #            - { property: 'description', type: 'fos_ckeditor', type_options: { config_name: 'full_config' }, css_class: 'event description' }
        #            - {type: 'tab', label: 'Evénements associés'}
        #            - {property: 'event', label: 'Evénements', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Site\Event' }}
        #    new:
        #        help: 'Notification : ajout'
        #        form_options: { validation_groups: ['Default', 'Event'] }
        #        fields:
        #            - '-id'
        #            - '-updatedAt'
        #    edit:
        #        help: 'Notification : modification'
        #        title: 'Edit notification'
        #        fields:
        #            - '-id'
        #            - '-updatedAt'
        User:
            class: App\Entity\Objet\User
            label: 'Utilisateurs'
            list:
                title: 'Liste des utilisateurs'
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Agent': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN' } } }
            edit:
                form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    - { property: 'plainPassword', type_options: { required: true} }
                form_options: { validation_groups: ['Registration'] }
        Menu:
            class: App\Entity\Objet\Menu
            label: 'Entrés de menu'
            list:
                title: 'Liste des menus'
            form:
                fields:
                    - libelle
                    - lien
                    - { property: 'categorie', type: 'choice', type_options: { multiple: false, choices: { 'Principale': 'main', 'Secondaire': 'second' } } }
                    - { property: 'type', type: 'choice', type_options: { multiple: false, choices: { 'Lien': 'lien', 'Libelle': 'libelle' } } }
                    - rang
                    - ref
            edit:
                form_options: { validation_groups: ['Default'] }
            new:
                form_options: { validation_groups: ['Default'] }